version: "3.8"

services:
  resources_service:
    container_name: resources-service
    build: .
    image: 224983445169.dkr.ecr.eu-north-1.amazonaws.com/resources-service:latest
    environment:
      DB_HOST: rings-quest-5.ck4o8yyu369l.eu-north-1.rds.amazonaws.com
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: postgres
      GAME_NAME: rings-quest
    ports:
      - "3102:3002"

  bars_service:
    container_name: bars-service
    build: .
    image: morsof48/bars-service:latest
    environment:
      DB_HOST: rings-quest-5.ck4o8yyu369l.eu-north-1.rds.amazonaws.com
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: postgres
      RESOURCES_PROVIDER_BASE_URL: http://resources_service:3002
    ports:
      - "3105:3005"
    depends_on:
      - resources_service

  levels_service:
    container_name: levels-service
    build: .
    image: morsof48/levels-service:latest
    environment:
      DB_HOST: rings-quest-5.ck4o8yyu369l.eu-north-1.rds.amazonaws.com
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: postgres
      BARS_PROVIDER_BASE_URL: http://bars_service:3005
    ports:
      - "3101:3001"
    depends_on:
      - bars_service

  players_service:
    container_name: players-service
    build: .
    image: morsof48/players-service:latest
    environment:
      DB_HOST: rings-quest-5.ck4o8yyu369l.eu-north-1.rds.amazonaws.com
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: postgres
      BARS_PROVIDER_BASE_URL: http://bars_service:3005
      RESOURCES_PROVIDER_BASE_URL: http://resources_service:3002
      LEVELS_PROVIDER_BASE_URL: http://levels_service:3001
    ports:
      - "3103:3003"
    depends_on:
      - resources_service
      - bars_service
      - levels_service
