version: "3.8"

services:
  resources_service:
    container_name: resources-service
    build: .
    image: morsof48/resources-service:latest
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: user
      DB_PASSWORD: admin
      DB_NAME: postgres
      GAME_NAME: rings-quest
    ports:
      - "3102:3002"
    depends_on:
      - db

  bars_service:
    container_name: bars-service
    build: .
    image: morsof48/bars-service:latest
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: user
      DB_PASSWORD: admin
      DB_NAME: postgres
      RESOURCES_PROVIDER_BASE_URL: http://resources_service:3002
    ports:
      - "3105:3005"
    depends_on:
      - db
      - resources_service

  levels_service:
    container_name: levels-service
    build: .
    image: morsof48/levels-service:latest
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: user
      DB_PASSWORD: admin
      DB_NAME: postgres
      BARS_PROVIDER_BASE_URL: http://bars_service:3005
    ports:
      - "3101:3001"
    depends_on:
      - db
      - bars_service

  players_service:
    container_name: players-service
    build: .
    image: morsof48/players-service:latest
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: user
      DB_PASSWORD: admin
      DB_NAME: postgres
      BARS_PROVIDER_BASE_URL: http://bars_service:3005
      RESOURCES_PROVIDER_BASE_URL: http://resources_service:3002
      LEVELS_PROVIDER_BASE_URL: http://levels_service:3001
    ports:
      - "3103:3003"
    depends_on:
      - db
      - resources_service
      - bars_service
      - levels_service

  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: mor@mor.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

  redis:
    container_name: redis
    image: redis:6.2-alpine

volumes:
  local_pgdata:
  pgadmin-data:
