version: "3.8"

services:
  levels_service:
    container_name: levels-service
    build: .
    image: morsof48/levels-service:latest
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: user
      DB_PASSWORD: admin
      DB_NAME: postgres
      RESOURCES_PROVIDER_BASE_URL: http://resources_service:3002
    ports:
      - "3101:3001"
    depends_on:
      - db
      - resources_service

  resources_service:
    container_name: resources_service
    build: .
    image: morsof48/resources-service:latest
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: user
      DB_PASSWORD: admin
      DB_NAME: postgres
      GAME_NAME: rings-quest
    ports:
      - "3102:3002"
    depends_on:
      - db

  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: mor@mor.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  redis:
    container_name: redis
    image: redis:6.2-alpine

volumes:
  local_pgdata:
  pgadmin-data:
